server:
  port: 8080
  servlet:
    context-path: /hello-world
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/helloworld?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: ENC(64BQZIlICBBQqoJjoI4M4TydImDf35dq)
    password: ENC(H+Vi10oa4qhuwRQIXpWgmXSgDTB+LgqusY5TT5+HbyM=)
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: HelloWorldHikari
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  banner:
    location: classpath:static/banner.txt
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
    password: xxx
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 100
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: hello-world
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
swagger:
  enabled: true
mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.zhw.helloworld.dal
  configuration:
    map-underscore-to-camel-case: true
jasypt:
  encryptor:
    password: hello-world
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
logging:
  config: classpath:logback-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
---
dubbo:
  application:
    name: web-controller
  registry:
    address: zookeeper://127.0.0.1:2181
