CREATE TABLE hello
(
    `id`   INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(20) DEFAULT NULL,
    `code` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = INNODB
  AUTO_INCREMENT = 8
  DEFAULT CHARSET = utf8;

CREATE TABLE world
(
    `id`   INT(10) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(20) DEFAULT NULL,
    `code` VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (`id`)
) ENGINE = INNODB
  AUTO_INCREMENT = 8
  DEFAULT CHARSET = utf8;